from sqlalchemy.orm import Session
from db.models import Series, Subseries
from core.exceptions import AppException, EntityNotFoundException
import os
import importlib.util

class SeriesService:
    @staticmethod
    def get_series_config(db: Session):
        series_list = db.query(Series).all()
        options = {}
        metadata = {}
        
        for s in series_list:
            options[s.name] = [sub.name for sub in s.subseries]
            metadata[s.name] = {
                "description": s.description or "No description available",
                "price_range": s.price_range or "Varies",
                "rarity": s.rarity or "Unknown"
            }
        
        return {
            "series_options": options,
            "series_metadata": metadata
        }

    @staticmethod
    def add_series(db: Session, name: str, description: str = None, price_range: str = None, rarity: str = None):
        existing = db.query(Series).filter(Series.name == name).first()
        if existing:
            raise AppException(f"Series '{name}' already exists")
            
        new_series = Series(
            name=name,
            description=description,
            price_range=price_range,
            rarity=rarity
        )
        db.add(new_series)
        db.commit()
        db.refresh(new_series)
        SeriesService._sync_legacy_config(db)
        return new_series

    @staticmethod
    def add_subseries(db: Session, series_name: str, subseries_name: str):
        series = db.query(Series).filter(Series.name == series_name).first()
        if not series:
            raise EntityNotFoundException("Series", series_name)
            
        existing_sub = db.query(Subseries).filter(
            Subseries.name == subseries_name, 
            Subseries.series_id == series.id
        ).first()
        if existing_sub:
            raise AppException(f"Subseries '{subseries_name}' already exists in '{series_name}'")
            
        new_sub = Subseries(name=subseries_name, series_id=series.id)
        db.add(new_sub)
        db.commit()
        SeriesService._sync_legacy_config(db)
        return new_sub

    @staticmethod
    def rename_series(db: Session, old_name: str, new_name: str):
        series = db.query(Series).filter(Series.name == old_name).first()
        if not series:
            raise EntityNotFoundException("Series", old_name)
            
        existing_new = db.query(Series).filter(Series.name == new_name).first()
        if existing_new:
            raise AppException(f"Series '{new_name}' already exists")
            
        series.name = new_name
        db.commit()
        SeriesService._sync_legacy_config(db)
        return series

    @staticmethod
    def _sync_legacy_config(db: Session):
        """
        Maintains the legacy series_config.py file for backward compatibility 
        with existing scripts that might still import it.
        """
        config = SeriesService.get_series_config(db)
        options = config["series_options"]
        metadata = config["series_metadata"]
        
        # Path to legacy config
        config_dir = os.path.join("pages", "series-management")
        if not os.path.exists(config_dir):
            return
            
        config_path = os.path.join(config_dir, "series_config.py")
        
        # Format strings for file writing (simplified version of legacy manage_series.py logic)
        options_str = str(options)
        metadata_str = str(metadata)
        
        content = f"""#!/usr/bin/env python3
# AUTO-GENERATED BY SeriesService - DO NOT EDIT MANUALLY
SERIES_OPTIONS = {options_str}
SERIES_METADATA = {metadata_str}

def get_all_series(): return list(SERIES_OPTIONS.keys())
def get_subseries(main_series): return SERIES_OPTIONS.get(main_series, [])
def get_series_info(main_series): return SERIES_METADATA.get(main_series, {{}})
"""
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(content)
